var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var swaggerUI = require('swagger-ui-express');
var swaggerJsdoc = require('swagger-jsdoc');
var options = {
  swaggerDefinition: {
    info: {
      title: 'User API',
      version: '1.0.0',
      description: 'user express API with autogenerated swagger doc',
    },
  },
  apis: ['./models/Users.js', './routes/users.js']
}
var specs = swaggerJsdoc(options);

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(specs));

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

//load mongoose
var mongoose = require('mongoose');
mongoose.Promise = global.Promise

//hubungkan ke Mongodb
mongoose.connect('mongodb://localhost/eradata')
  .then(() => console.log('berhasil terhubung dengan Mongodb'))
  .catch((err) => console.error(err));

module.exports = app;
